import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Code Hike v1 Starter",
  description: "Generated by create next app",
}

interface  ArticleLayoutProps {
children: React.ReactNode
}

export default function ArticleLayout({
  children,
}: ArticleLayoutProps) {
  return (
    <div
      data-slot="article-layout"
      className="dark bg-zinc-950 prose prose-invert mx-auto py-24 max-w-5xl px-4"
    >
      {children}
    </div>
  )
}
