import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Code Hike v1 Starter',
  description: 'Generated by create next app',
}

interface ArticleLayoutProps {
  children: React.ReactNode
}

export default function ArticleLayout({ children }: ArticleLayoutProps) {
  return (
    <div
      data-slot="article-layout"
      className="dark prose prose-invert mx-auto max-w-5xl bg-zinc-950 px-4 py-24"
    >
      {children}
    </div>
  )
}
