import type { Metadata } from 'next'
import { Geist, Geist_Mono, Inter_Tight, Syncopate } from 'next/font/google'

import { cx } from '@/lib/utils'

import '@/styles/globals.css'

import App from 'next/app'

import { PageLayoutProps } from '@/lib/types'
import { AppProvider } from '@/components/app-provider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const syncopate = Syncopate({
  weight: ['400'],
  variable: '--font-syncopate',
  subsets: ['latin'],
})

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: PageLayoutProps) {
  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <body
        className={cx(
          geistSans.variable,
          geistMono.variable,
          syncopate.variable,
          'bg-page text-cnt-primary min-h-full font-sans antialiased',
        )}
      >
        <AppProvider defaultThemeGrayColor="sand" defaultThemeAccentColor="lime">
          {children}
        </AppProvider>
      </body>
    </html>
  )
}
